server:
  port: 28098
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: ${config.repo.uri:https://github.com/waylon-lee/config-repo}
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:28081/eureka/
