server:
  port: 28083
eureka:
  instance:
     prefer-ip-address: true #以IP地址注册到服务中心
  client:
    service-url:
      defaultZone: http://127.0.0.1:28081/eureka/
spring:
  application:
    name: service-provide


